import pandas as pd

INPUT_FILE = "results/intent_manual_review.csv"
OUTPUT_FILE = "results/intent_manual_review.csv"

df = pd.read_csv(INPUT_FILE)

labels = [
    "REFUND_ISSUE", "DELIVERY_DELAY", "WRONG_DELIVERY", "PACKAGE_NOT_RECEIVED",
    "DELIVERY_INSTRUCTIONS", "PACKAGE_NOT_RECEIVED", "CUSTOMER_SERVICE", "OTHER",
    "OTHER", "DELIVERY_DELAY", "DELIVERY_ESTIMATE", "OTHER", "DELIVERY_DELAY",
    "CUSTOMER_SERVICE", "OTHER", "ORDER_CANCELLATION", "PACKAGE_NOT_RECEIVED",
    "ACCOUNT_PROBLEM", "ORDER_NOT_DISPATCHED", "DELIVERY_DELAY",
    "CUSTOMER_SERVICE", "DIGITAL_DEVICE_ISSUE", "RETURN_ISSUE", "CUSTOMER_SERVICE",
    "CUSTOMER_SERVICE", "ORDER_NOT_DISPATCHED", "DIGITAL_DEVICE_ISSUE",
    "DIGITAL_DEVICE_ISSUE", "CUSTOMER_SERVICE", "PRIME_MEMBERSHIP",
    "ACCOUNT_PROBLEM", "CUSTOMER_SERVICE", "PAYMENT_PROBLEM", "CUSTOMER_SERVICE",
    "ORDER_PROBLEM", "DELIVERY_DELAY", "ORDER_NOT_DISPATCHED",
    "DELIVERY_ADDRESS_ISSUE", "CUSTOMER_SERVICE", "REPLACEMENT_ISSUE",
    "CUSTOMER_SERVICE", "SELLER_ISSUE", "DELIVERY_DELAY", "CUSTOMER_SERVICE",
    "DELIVERY_ISSUE", "CUSTOMER_SERVICE", "CUSTOMER_SERVICE", "PACKAGING_ISSUE",
    "DELIVERY_DELAY", "DELIVERY_DELAY", "PACKAGE_NOT_RECEIVED",
    "LINK_OR_WEBSITE_ISSUE", "DIGITAL_DEVICE_ISSUE", "EMAIL_ISSUE",
    "DELIVERY_ISSUE", "ACCOUNT_PROBLEM", "DELIVERY_ESTIMATE", "REFUND_ISSUE",
    "DELIVERY_DELAY", "DELIVERY_INSTRUCTIONS", "CUSTOMER_SERVICE",
    "ACCOUNT_PROBLEM", "PACKAGE_NOT_RECEIVED", "TRACKING_ISSUE", "CUSTOMER_SERVICE",
    "ORDER_NOT_DISPATCHED", "DELIVERY_INSTRUCTIONS", "ACCOUNT_SECURITY",
    "PRICE_MATCH_ISSUE", "DIGITAL_DEVICE_ISSUE", "PRIME_DELIVERY_ISSUE", "OTHER",
    "PACKAGE_NOT_RECEIVED", "OTHER", "DIGITAL_DEVICE_ISSUE", "CUSTOMER_SERVICE",
    "DELIVERY_ESTIMATE", "DELIVERY_ESTIMATE", "PAYMENT_ISSUE",
    "DELIVERY_INSTRUCTIONS", "CUSTOMER_SERVICE", "CUSTOMER_SERVICE",
    "PACKAGE_NOT_RECEIVED", "CUSTOMER_SERVICE", "DELIVERY_DELAY", "CLAIM_ISSUE",
    "DELIVERY_DELAY", "OTHER", "ACCOUNT_SECURITY", "CUSTOMER_SERVICE",
    "DELIVERY_ESTIMATE", "OTHER", "ACCOUNT_PROBLEM", "PRICE_ISSUE", "OTHER",
    "TRACKING_ISSUE", "OTHER", "OTHER", "OTHER", "DIGITAL_DEVICE_ISSUE",
    "PRIME_DELIVERY_ISSUE", "OTHER", "ORDER_ON_HOLD", "CUSTOMER_SERVICE",
    "DELIVERY_DELAY", "ACCOUNT_PROBLEM", "OTHER", "DELIVERY_ISSUE", "OTHER",
    "CUSTOMER_SERVICE", "FEEDBACK", "ORDER_NOT_FULFILLED", "SELLER_ISSUE",
    "PRIME_CHARGE_ISSUE", "OTHER", "REPLACEMENT_ISSUE", "RETURN_ISSUE",
    "DELIVERY_DELAY", "ADDRESS_ISSUE", "DIGITAL_DEVICE_ISSUE", "CUSTOMER_SERVICE",
    "LINK_OR_WEBSITE_ISSUE", "DELIVERY_ISSUE", "DELIVERY_ISSUE",
    "PACKAGE_NOT_RECEIVED", "FEEDBACK", "SELLER_ISSUE", "DIGITAL_DEVICE_ISSUE",
    "PACKAGE_NOT_RECEIVED", "REVIEW_ISSUE", "OTHER", "DELIVERY_ESTIMATE", "OTHER",
    "CUSTOMER_SERVICE", "REFUND_ISSUE", "SELLER_ISSUE", "DIGITAL_DEVICE_ISSUE",
    "OTHER", "RETURN_ISSUE", "ORDER_CANCELLATION", "CODE_NOT_RECEIVED",
    "EMAIL_ISSUE", "OTHER", "FRAUD_SECURITY_ISSUE", "CUSTOMER_SERVICE",
    "PRODUCT_INFORMATION", "OTHER", "PRIME_DELIVERY_ISSUE", "ACCOUNT_SECURITY",
    "CUSTOMER_SERVICE", "FRAUD_SECURITY_ISSUE", "OTHER", "DELIVERY_ESTIMATE",
    "CUSTOMER_SERVICE", "DELIVERY_DELAY", "ACCOUNT_PROBLEM", "CUSTOMER_SERVICE",
    "PACKAGE_NOT_RECEIVED", "FEEDBACK", "PAYMENT_ISSUE",
    "CUSTOMER_SERVICE", "CALLBACK_ISSUE", "PRODUCT_INFORMATION", "CUSTOMER_SERVICE",
    "DELIVERY_ISSUE", "ORDER_NOT_DISPATCHED", "LINK_OR_WEBSITE_ISSUE",
    "REPLACEMENT_ISSUE", "LINK_OR_WEBSITE_ISSUE", "LINK_OR_WEBSITE_ISSUE",
    "CALLBACK_ISSUE", "CUSTOMER_SERVICE", "DIGITAL_DEVICE_ISSUE",
    "CUSTOMER_SERVICE", "SELLER_ISSUE", "DELIVERY_ISSUE", "DELIVERY_ISSUE",
    "DELIVERY_DELAY", "DELIVERY_ISSUE", "OTHER", "OTHER", "PRODUCT_INFORMATION",
    "ORDER_NOT_DISPATCHED", "DELIVERY_DELAY", "OTHER", "WRONG_DELIVERY",
    "CALLBACK_ISSUE", "ORDER_CANCELLATION", "OTHER", "RETURN_ISSUE",
    "DELIVERY_INSTRUCTIONS", "TRACKING_ISSUE", "LINK_OR_WEBSITE_ISSUE",
    "SELLER_ISSUE", "CUSTOMER_SERVICE", "DELIVERY_ISSUE", "DELIVERY_ISSUE",
    "EMAIL_ISSUE", "CUSTOMER_SERVICE", "FEEDBACK"
]

if len(labels) != len(df):
    raise ValueError(
        f"Expected 200 labels, but CSV has {len(df)} rows."
    )

df["intent"] = labels

df.to_csv(OUTPUT_FILE, index=False)

print("INTENTS FILLED")
print("=" * 40)
print("Examples:", len(df))
print("Saved to:", OUTPUT_FILE)

print("\nINTENT FREQUENCY")
print("=" * 40)
print(df["intent"].value_counts())